server:
  address: tcp://0.0.0.0:9091

log:
  level: info

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: "gitea.local.test"
      policy: one_factor
    - domain: "grafana.local.test"
      policy: one_factor
    - domain: "authelia.local.test"
      policy: one_factor

session:
  name: authelia_session
  secret: secrete_value
  expiration: 3600
  inactivity: 300
  same_site: lax
  cookies:
    - domain: ".local.test"
      authelia_url: https://authelia.local.test
      default_redirection_url: https://gitea.local.test

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: encryptionkey_value

notifier:
  filesystem:
    filename: /config/notification.txt

identity_validation:
  reset_password:
    jwt_secret: jwt_value

